FROM alpine:latest

# base stuff for claude code
RUN apk add --no-cache curl bash jq libstdc++ libgcc

# all other packages I want inside the containers
RUN apk add --no-cache rust cargo git jujutsu ripgrep nushell nodejs npm

RUN apk add --no-cache openssh

RUN adduser -D maki

USER maki
WORKDIR /home/maki

RUN mkdir --parents /home/maki/.local/bin

RUN curl -fsSL https://maki.sh/install.sh | MAKI_INSTALL_DIR="/home/maki/.local/bin" sh

ENV PATH="/home/maki/.local/bin:${PATH}"

ENTRYPOINT ["maki"]
