FROM alpine:latest

# base stuff for claude code
RUN apk add --no-cache curl bash jq libstdc++ libgcc

# all other packages I want inside the containers
RUN apk add --no-cache rust cargo git jujutsu ripgrep nushell nodejs npm

RUN apk add --no-cache openssh

RUN npm install --global @mariozechner/pi-coding-agent

RUN adduser -D pi

USER pi
WORKDIR /home/pi

ENTRYPOINT ["pi"]
